/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.neu.userinterface.patientRole;

import com.neu.business.EcoSystem;
import com.neu.business.enterprise.Enterprise;
import com.neu.business.organization.DoctorOrganization;
import com.neu.business.organization.Organization;
import com.neu.business.userAccount.UserAccount;
import com.neu.business.workQueue.EmergencyCallRequest;
import com.neu.business.workQueue.WorkRequest;
import com.neu.userinterface.util.UIUtilities;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author raunak
 */
public class PatientsDashboard extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem ecoSystem;
    private Enterprise enterprise;
    private UserAccount userAccount;
    /**
     * Creates new form ManageEnterpriseJPanel
     */
    public PatientsDashboard(JPanel userProcessContainer, EcoSystem system,Enterprise enterprise,UserAccount userAccount) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecoSystem = system;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        UIUtilities.initButtonComponents(redBtn);
        UIUtilities.initButtonComponents(yellowBtn);
        UIUtilities.initButtonComponents(greenBtn);
    }

    public PatientsDashboard(EcoSystem ecoSystem) {
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        greenBtn = new javax.swing.JButton();
        redBtn = new javax.swing.JButton();
        yellowBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder1 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder1.setShowLeftShadow(true);
        dropShadowBorder1.setShowTopShadow(true);
        setBorder(dropShadowBorder1);
        setPreferredSize(new java.awt.Dimension(410, 537));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        greenBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imgs/button_round_green.png"))); // NOI18N
        greenBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        greenBtn.setPreferredSize(new java.awt.Dimension(200, 200));
        greenBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                greenBtnActionPerformed(evt);
            }
        });
        add(greenBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 100, 100));

        redBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imgs/button-glow.gif"))); // NOI18N
        redBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        redBtn.setPreferredSize(new java.awt.Dimension(200, 200));
        redBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redBtnActionPerformed(evt);
            }
        });
        add(redBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 110, 110));

        yellowBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imgs/button_round_yellow.png"))); // NOI18N
        yellowBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        yellowBtn.setPreferredSize(new java.awt.Dimension(200, 200));
        yellowBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                yellowBtnMouseEntered(evt);
            }
        });
        yellowBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yellowBtnActionPerformed(evt);
            }
        });
        add(yellowBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 100, 100));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel1.setText("My Reports");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel2.setText("Emergency");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel3.setText("My Appointments");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, -1, -1));
    }// </editor-fold>//GEN-END:initComponents
    public WorkRequest addRequest(){
        EmergencyCallRequest emergencyCallRequest = new EmergencyCallRequest();
        emergencyCallRequest.setMessage("Medical Emergency at" + userAccount.getPatients().getAddress());
        emergencyCallRequest.setSender(userAccount);
        emergencyCallRequest.setStatus("Pending");

        Organization org = null;
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
            if (organization instanceof DoctorOrganization) {
                org = organization;
                break;
            }
        }
        if (org != null) {
            
            //org.getUserAccountDirectory().searchUserAccount(doctor).getWorkQueue().getWorkRequestList().add(appointmentRequest);
            userAccount.getWorkQueue().getWorkRequestList().add(emergencyCallRequest);
        }
        return emergencyCallRequest;
    }
    private void redBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redBtnActionPerformed
        // TODO add your handling code here:
        //search nearest Doctor and make a phone call
        EmergencyCallRequest workRequest = (EmergencyCallRequest)addRequest();
        CallHospitalAdminPanel panel = new CallHospitalAdminPanel(ecoSystem,enterprise,userProcessContainer,userAccount,workRequest);
        userProcessContainer.add("CallHospitalAdminPanel", panel);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);

    }//GEN-LAST:event_redBtnActionPerformed

    private void yellowBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yellowBtnActionPerformed
       //Book an Appointment
        SearchDoctorPanel panel = new SearchDoctorPanel(ecoSystem,enterprise,userProcessContainer,userAccount);
        userProcessContainer.add("SearchDoctorPanel", panel);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_yellowBtnActionPerformed

    private void yellowBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yellowBtnMouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_yellowBtnMouseEntered

    private void greenBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_greenBtnActionPerformed
        // TODO add your handling code here:
        
        MyReportPanel panel = new MyReportPanel(ecoSystem,enterprise,userProcessContainer,userAccount);
        userProcessContainer.add("MyReportPanel", panel);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_greenBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton greenBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton redBtn;
    private javax.swing.JButton yellowBtn;
    // End of variables declaration//GEN-END:variables
}
