/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.neu.userinterface.patientRole;

import com.neu.business.EcoSystem;
import com.neu.business.employee.Employee;
import com.neu.business.enterprise.Enterprise;
import com.neu.business.organization.DoctorOrganization;
import com.neu.business.organization.Organization;
import com.neu.business.userAccount.UserAccount;
import com.neu.business.workQueue.AppointmentRequest;
import com.neu.business.workQueue.WorkRequest;
import com.neu.userinterface.util.UIUtilities;
import java.awt.CardLayout;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.Enumeration;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author raunak
 */
public class ReviewDoctorPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem ecoSystem;
    private Employee doctor;
    private UserAccount userAccount;
    private Enterprise enterprise;
    private int starCnt = 0;

    /**
     * Creates new form ManageEnterpriseJPanel
     */
    public ReviewDoctorPanel(JPanel userProcessContainer, EcoSystem system,
            Enterprise enterprise, Employee doctor, UserAccount ua) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecoSystem = system;
        this.doctor = doctor;
        this.userAccount = ua;
        this.enterprise = enterprise;
        docName.setText(doctor.getName());
        speciality.setText(doctor.getSpeciality());
        UIUtilities.initButtonComponents(star1);
        UIUtilities.initButtonComponents(star2);
        UIUtilities.initButtonComponents(star3);
        UIUtilities.initButtonComponents(star4);
        UIUtilities.initButtonComponents(star5);
        
        msgLabel.setVisible(false);
    }

    public void populateRequestTable() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        schedulePanel = new javax.swing.JPanel();
        msgLabel = new javax.swing.JLabel();
        profilePicture = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        docName = new javax.swing.JLabel();
        speciality = new javax.swing.JLabel();
        reviews = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        schedule = new javax.swing.JLabel();
        schedule1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        reviewCommentsTxt = new javax.swing.JTextArea();
        star3 = new javax.swing.JToggleButton();
        star2 = new javax.swing.JToggleButton();
        star4 = new javax.swing.JToggleButton();
        star5 = new javax.swing.JToggleButton();
        star1 = new javax.swing.JToggleButton();
        rateMyDoctorBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder1 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder1.setShowLeftShadow(true);
        dropShadowBorder1.setShowTopShadow(true);
        setBorder(dropShadowBorder1);
        setPreferredSize(new java.awt.Dimension(418, 537));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        schedulePanel.setBackground(new java.awt.Color(255, 255, 255));
        schedulePanel.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());
        schedulePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        msgLabel.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        msgLabel.setForeground(new java.awt.Color(255, 0, 51));
        msgLabel.setText("jLabel1");
        schedulePanel.add(msgLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 260, -1));

        profilePicture.setText("jLabel1");
        profilePicture.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        schedulePanel.add(profilePicture, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 90, 110));

        jLabel1.setText("Prescription :");
        schedulePanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 130, 60));

        jLabel2.setText("Turn Around Time");
        schedulePanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, -1, -1));

        add(schedulePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 300, 190));

        jPanel2.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());

        docName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        docName.setText("jLabel1");
        jPanel2.add(docName);

        speciality.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        speciality.setText("jLabel2");
        jPanel2.add(speciality);

        reviews.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        reviews.setText("jLabel2");
        jPanel2.add(reviews);

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 300, 40));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());

        schedule.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        schedule.setText("Rate your Doctor");

        schedule1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        schedule1.setText("Comments");

        reviewCommentsTxt.setColumns(20);
        reviewCommentsTxt.setLineWrap(true);
        reviewCommentsTxt.setRows(5);
        reviewCommentsTxt.setTabSize(1);
        reviewCommentsTxt.setWrapStyleWord(true);
        jScrollPane1.setViewportView(reviewCommentsTxt);

        star3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imgs/grey_star.gif"))); // NOI18N
        star3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                star3ActionPerformed(evt);
            }
        });

        star2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imgs/grey_star.gif"))); // NOI18N
        star2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                star2ActionPerformed(evt);
            }
        });

        star4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imgs/grey_star.gif"))); // NOI18N
        star4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                star4ActionPerformed(evt);
            }
        });

        star5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imgs/grey_star.gif"))); // NOI18N
        star5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                star5ActionPerformed(evt);
            }
        });

        star1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imgs/grey_star.gif"))); // NOI18N
        star1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                star1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(schedule1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(schedule)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(star1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(star2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(star3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(star4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addComponent(star5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(schedule)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(star3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(star2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(star4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(star5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(star1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(schedule1)
                        .addGap(0, 51, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 300, 210));

        rateMyDoctorBtn.setText("Rate My Doctor");
        rateMyDoctorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rateMyDoctorBtnActionPerformed(evt);
            }
        });
        add(rateMyDoctorBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 500, 418, 40));

        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imgs/Arrow-Back-3-icon.png"))); // NOI18N
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 3, 430, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void rateMyDoctorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rateMyDoctorBtnActionPerformed
       
        doctor.getReviewCnt().add(starCnt);
       doctor.setReviewComments(reviewCommentsTxt.getText());
       doctor.calculateAvgReviews();
       JOptionPane.showMessageDialog(null, "Thank you for your feedback", "Success", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_rateMyDoctorBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed

    private void star2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_star2ActionPerformed
        // TODO add your handling code here:
        if (star2.isSelected()) {
            star2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imgs/star_50_50.gif")));
            star1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imgs/star_50_50.gif")));
            star3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imgs/grey_star.gif")));
            star4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imgs/grey_star.gif")));
            star5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imgs/grey_star.gif")));
            star1.setSelected(true);
            star2.setSelected(true);
            star3.setSelected(false);
            star4.setSelected(false);
            star5.setSelected(false);
            starCnt = 2;
        } else {
            star2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imgs/grey_star.gif")));
            star1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imgs/star_50_50.gif")));
            star3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imgs/grey_star.gif")));
            star4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imgs/grey_star.gif")));
            star5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imgs/grey_star.gif")));
            star1.setSelected(true);
            star2.setSelected(false);
            star3.setSelected(false);
            star4.setSelected(false);
            star5.setSelected(false);
            starCnt =1;
        }
    }//GEN-LAST:event_star2ActionPerformed

    private void star1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_star1ActionPerformed
        // TODO add your handling code here:
        if (star1.isSelected()) {
            star1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imgs/star_50_50.gif")));
            star2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imgs/grey_star.gif")));
            star3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imgs/grey_star.gif")));
            star4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imgs/grey_star.gif")));
            star5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imgs/grey_star.gif")));
            star1.setSelected(true);
            star2.setSelected(false);
            star3.setSelected(false);
            star4.setSelected(false);
            star5.setSelected(false);
            starCnt = 1;
        } else {
            star1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imgs/grey_star.gif")));
            star2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imgs/grey_star.gif")));
            star3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imgs/grey_star.gif")));
            star4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imgs/grey_star.gif")));
            star5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imgs/grey_star.gif")));
            star1.setSelected(false);
            star2.setSelected(false);
            star3.setSelected(false);
            star4.setSelected(false);
            star5.setSelected(false);
            starCnt = 0;
        }
    }//GEN-LAST:event_star1ActionPerformed

    private void star3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_star3ActionPerformed
        // TODO add your handling code here:
        if (star3.isSelected()) {
            star1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imgs/star_50_50.gif")));
            star2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imgs/star_50_50.gif")));
            star3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imgs/star_50_50.gif")));
            star4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imgs/grey_star.gif")));
            star5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imgs/grey_star.gif")));
            star1.setSelected(true);
            star2.setSelected(true);
            star3.setSelected(true);
            star4.setSelected(false);
            star5.setSelected(false);
            starCnt = 3;
        } else {
            star1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imgs/star_50_50.gif")));
            star2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imgs/star_50_50.gif")));
            star3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imgs/grey_star.gif")));
            star4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imgs/grey_star.gif")));
            star5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imgs/grey_star.gif")));
            star1.setSelected(true);
            star2.setSelected(true);
            star3.setSelected(false);
            star4.setSelected(false);
            star5.setSelected(false);
            starCnt = 2;
        }
    }//GEN-LAST:event_star3ActionPerformed

    private void star4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_star4ActionPerformed
        // TODO add your handling code here:
        if (star3.isSelected()) {
            star1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imgs/star_50_50.gif")));
            star2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imgs/star_50_50.gif")));
            star3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imgs/star_50_50.gif")));
            star4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imgs/star_50_50.gif")));
            star5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imgs/grey_star.gif")));
            star1.setSelected(true);
            star2.setSelected(true);
            star3.setSelected(true);
            star4.setSelected(true);
            star5.setSelected(false);
            starCnt = 4;
        } else {
            star1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imgs/star_50_50.gif")));
            star2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imgs/star_50_50.gif")));
            star3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imgs/star_50_50.gif")));
            star4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imgs/grey_star.gif")));
            star5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imgs/grey_star.gif")));
            star1.setSelected(true);
            star2.setSelected(true);
            star3.setSelected(true);
            star4.setSelected(false);
            star5.setSelected(false);
            starCnt = 3;
        }
    }//GEN-LAST:event_star4ActionPerformed

    private void star5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_star5ActionPerformed
        // TODO add your handling code here:
        if (star3.isSelected()) {
            star1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imgs/star_50_50.gif")));
            star2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imgs/star_50_50.gif")));
            star3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imgs/star_50_50.gif")));
            star4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imgs/star_50_50.gif")));
            star5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imgs/star_50_50.gif")));
            star1.setSelected(true);
            star2.setSelected(true);
            star3.setSelected(true);
            star4.setSelected(true);
            star5.setSelected(true);
            starCnt = 5;
        } else {
            star1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imgs/star_50_50.gif")));
            star2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imgs/star_50_50.gif")));
            star3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imgs/star_50_50.gif")));
            star4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imgs/star_50_50.gif")));
            star5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imgs/grey_star.gif")));
            star1.setSelected(true);
            star2.setSelected(true);
            star3.setSelected(true);
            star4.setSelected(true);
            star5.setSelected(false);
            starCnt = 4;

        }
    }//GEN-LAST:event_star5ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel docName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel msgLabel;
    private javax.swing.JLabel profilePicture;
    private javax.swing.JButton rateMyDoctorBtn;
    private javax.swing.JTextArea reviewCommentsTxt;
    private javax.swing.JLabel reviews;
    private javax.swing.JLabel schedule;
    private javax.swing.JLabel schedule1;
    private javax.swing.JPanel schedulePanel;
    private javax.swing.JLabel speciality;
    private javax.swing.JToggleButton star1;
    private javax.swing.JToggleButton star2;
    private javax.swing.JToggleButton star3;
    private javax.swing.JToggleButton star4;
    private javax.swing.JToggleButton star5;
    // End of variables declaration//GEN-END:variables
}
