/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.neu.userinterface.patientRole;

import com.neu.business.EcoSystem;
import com.neu.business.employee.Employee;
import com.neu.business.enterprise.Enterprise;
import com.neu.business.network.Network;
import com.neu.business.organization.Organization;
import com.neu.business.userAccount.UserAccount;
import com.neu.userinterface.util.UIUtilities;
import java.awt.CardLayout;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JPanel;

/**
 *
 * @author raunak
 */
public class SearchDoctorPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem ecoSystem;
    private Enterprise enterprise;
    private UserAccount userAccount;

    /**
     * Creates new form ManageEnterpriseJPanel
     */
    public SearchDoctorPanel(EcoSystem ecoSystem, Enterprise enterprise, JPanel userProcessContainer, UserAccount userAccount) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecoSystem = ecoSystem;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        UIUtilities.initButtonComponents(backBtn);
        UIUtilities.initButtonComponents(searchBtn);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchTxt = new javax.swing.JTextField();
        backBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        gyaneLbl = new javax.swing.JLabel();
        DermatologistLbl = new javax.swing.JLabel();
        dentistLbl = new javax.swing.JLabel();
        homeopathLbl = new javax.swing.JLabel();
        ayurvedaLbl = new javax.swing.JLabel();
        gastroenterologistLbl = new javax.swing.JLabel();
        cardiologistLbl = new javax.swing.JLabel();
        gastroenterologistLbl1 = new javax.swing.JLabel();
        entspecialistLbl = new javax.swing.JLabel();
        gastroenterologistLbl2 = new javax.swing.JLabel();
        searchBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder1 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder1.setShowLeftShadow(true);
        dropShadowBorder1.setShowTopShadow(true);
        setBorder(dropShadowBorder1);
        setPreferredSize(new java.awt.Dimension(418, 537));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        searchTxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        searchTxt.setForeground(new java.awt.Color(153, 153, 153));
        searchTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        searchTxt.setText("Specialities");
        searchTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        searchTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchTxtFocusLost(evt);
            }
        });
        add(searchTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 270, 30));

        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imgs/Arrow-Back-3-icon.png"))); // NOI18N
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder2 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder2.setShadowColor(new java.awt.Color(204, 204, 204));
        dropShadowBorder2.setShowLeftShadow(true);
        dropShadowBorder2.setShowTopShadow(true);
        jPanel1.setBorder(dropShadowBorder2);
        jPanel1.setAutoscrolls(true);
        jPanel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 420));

        gyaneLbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        gyaneLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imgs/doctor-icon.png"))); // NOI18N
        gyaneLbl.setText("Gynecologist/Obstetrician");
        gyaneLbl.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());
        gyaneLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gyaneLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gyaneLblMouseClicked(evt);
            }
        });

        DermatologistLbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        DermatologistLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imgs/doctor-icon.png"))); // NOI18N
        DermatologistLbl.setText("Dermatologist");
        DermatologistLbl.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());
        DermatologistLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DermatologistLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DermatologistLblMouseClicked(evt);
            }
        });

        dentistLbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dentistLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imgs/doctor-icon.png"))); // NOI18N
        dentistLbl.setText("Dentist");
        dentistLbl.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());
        dentistLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dentistLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dentistLblMouseClicked(evt);
            }
        });

        homeopathLbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        homeopathLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imgs/doctor-icon.png"))); // NOI18N
        homeopathLbl.setText("Homeopath");
        homeopathLbl.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());
        homeopathLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homeopathLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeopathLblMouseClicked(evt);
            }
        });

        ayurvedaLbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ayurvedaLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imgs/doctor-icon.png"))); // NOI18N
        ayurvedaLbl.setText("Ayurveda");
        ayurvedaLbl.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());
        ayurvedaLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ayurvedaLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ayurvedaLblMouseClicked(evt);
            }
        });

        gastroenterologistLbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        gastroenterologistLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imgs/doctor-icon.png"))); // NOI18N
        gastroenterologistLbl.setText("Gastroenterologist");
        gastroenterologistLbl.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());
        gastroenterologistLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gastroenterologistLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gastroenterologistLblMouseClicked(evt);
            }
        });

        cardiologistLbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cardiologistLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imgs/doctor-icon.png"))); // NOI18N
        cardiologistLbl.setText("Cardiologist");
        cardiologistLbl.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());
        cardiologistLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cardiologistLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cardiologistLblMouseClicked(evt);
            }
        });

        gastroenterologistLbl1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        gastroenterologistLbl1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imgs/doctor-icon.png"))); // NOI18N
        gastroenterologistLbl1.setText("Opthalmalogist");
        gastroenterologistLbl1.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());
        gastroenterologistLbl1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gastroenterologistLbl1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gastroenterologistLbl1MouseClicked(evt);
            }
        });

        entspecialistLbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        entspecialistLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imgs/doctor-icon.png"))); // NOI18N
        entspecialistLbl.setText("ENT specialist");
        entspecialistLbl.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());
        entspecialistLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        entspecialistLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                entspecialistLblMouseClicked(evt);
            }
        });

        gastroenterologistLbl2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        gastroenterologistLbl2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imgs/doctor-icon.png"))); // NOI18N
        gastroenterologistLbl2.setText("General Physician");
        gastroenterologistLbl2.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());
        gastroenterologistLbl2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gastroenterologistLbl2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gastroenterologistLbl2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dentistLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(gyaneLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
            .addComponent(DermatologistLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(homeopathLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(gastroenterologistLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ayurvedaLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(cardiologistLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(gastroenterologistLbl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(entspecialistLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(gastroenterologistLbl2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dentistLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(gyaneLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(DermatologistLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(homeopathLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ayurvedaLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cardiologistLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gastroenterologistLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(entspecialistLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gastroenterologistLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gastroenterologistLbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 280, 400));

        searchBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imgs/search-icon.png"))); // NOI18N
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });
        add(searchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 30, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void searchTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchTxtFocusGained
        // TODO add your handling code here:
        UIUtilities.changeFontColor(evt, Color.BLACK, Color.WHITE);
    }//GEN-LAST:event_searchTxtFocusGained

    private void searchTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchTxtFocusLost
        // TODO add your handling code here:
        if (searchTxt.getText().equals("")) {
            searchTxt.setText("Username");
            UIUtilities.changeFontColor(evt, new Color(240, 240, 240), Color.WHITE);
        }
    }//GEN-LAST:event_searchTxtFocusLost

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
        getDoctorList(searchTxt.getText());
    }//GEN-LAST:event_searchBtnActionPerformed

    private void dentistLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dentistLblMouseClicked
        // TODO add your handling code here:
        getDoctorList("dentist");
    }//GEN-LAST:event_dentistLblMouseClicked

    private void gyaneLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gyaneLblMouseClicked
        // TODO add your handling code here:
        getDoctorList("gyne");
    }//GEN-LAST:event_gyaneLblMouseClicked

    private void DermatologistLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DermatologistLblMouseClicked
        // TODO add your handling code here:
        getDoctorList("derma");
    }//GEN-LAST:event_DermatologistLblMouseClicked

    private void homeopathLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeopathLblMouseClicked
        // TODO add your handling code here:
        getDoctorList("homeo");
    }//GEN-LAST:event_homeopathLblMouseClicked

    private void ayurvedaLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ayurvedaLblMouseClicked
        // TODO add your handling code here:
        getDoctorList("ayur");
    }//GEN-LAST:event_ayurvedaLblMouseClicked

    private void cardiologistLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cardiologistLblMouseClicked
        // TODO add your handling code here:
        getDoctorList("cardio");
    }//GEN-LAST:event_cardiologistLblMouseClicked

    private void gastroenterologistLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gastroenterologistLblMouseClicked
        // TODO add your handling code here:
        getDoctorList("gastro");
    }//GEN-LAST:event_gastroenterologistLblMouseClicked

    private void entspecialistLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entspecialistLblMouseClicked
        // TODO add your handling code here:
        getDoctorList("ENT specialist");
    }//GEN-LAST:event_entspecialistLblMouseClicked

    private void gastroenterologistLbl1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gastroenterologistLbl1MouseClicked
        // TODO add your handling code here:
        getDoctorList("optha");
    }//GEN-LAST:event_gastroenterologistLbl1MouseClicked

    private void gastroenterologistLbl2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gastroenterologistLbl2MouseClicked
        // TODO add your handling code here:
        getDoctorList("gen");
    }//GEN-LAST:event_gastroenterologistLbl2MouseClicked
    private void getDoctorList(String searchString) {
        ArrayList<Employee> doctors = new ArrayList<>();
        doctors.clear();

        Organization myDocOrg = enterprise.getOrganizationDirectory().searchOrganization(Organization.Type.Doctor);
        doctors = myDocOrg.getEmployeeDirectory().searchEmployee(searchString);

        SearchResultPanel panel = new SearchResultPanel(userProcessContainer, ecoSystem, enterprise, doctors, userAccount);
        userProcessContainer.add("SearchResultPanel", panel);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DermatologistLbl;
    private javax.swing.JLabel ayurvedaLbl;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel cardiologistLbl;
    private javax.swing.JLabel dentistLbl;
    private javax.swing.JLabel entspecialistLbl;
    private javax.swing.JLabel gastroenterologistLbl;
    private javax.swing.JLabel gastroenterologistLbl1;
    private javax.swing.JLabel gastroenterologistLbl2;
    private javax.swing.JLabel gyaneLbl;
    private javax.swing.JLabel homeopathLbl;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField searchTxt;
    // End of variables declaration//GEN-END:variables
}
