/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.neu.userInterface.systemAdminWorkArea;

import com.neu.business.EcoSystem;
import com.neu.business.employee.Employee;
import com.neu.business.enterprise.Enterprise;
import com.neu.business.network.Network;
import com.neu.business.role.AdminRole;

import com.neu.business.userAccount.UserAccount;
import com.neu.userinterface.util.UIUtilities;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author raunak
 */
public class ManageEnterpriseAdminJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem system;

    /**
     * Creates new form ManageEnterpriseJPanel
     */
    public ManageEnterpriseAdminJPanel(EcoSystem e) {
        initComponents();

        this.userProcessContainer = userProcessContainer;
        this.system = e;

        populateTable();
        populateNetworkComboBox();
    }

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) enterpriseJTable.getModel();

        model.setRowCount(0);
        for (Network network : system.getNetworkList()) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                for (UserAccount userAccount : enterprise.getUserAccountDirectory().getUserAccountList()) {
                    Object[] row = new Object[4];
                    row[0] = enterprise.getName();
                    row[1] = network.getName();
                    row[2] = userAccount.getUsername();
                    row[3] = userAccount.getEmployee().getMobileNum();
                    model.addRow(row);
                }
            }
        }
    }

    private void populateNetworkComboBox() {
        networkJComboBox.removeAllItems();

        for (Network network : system.getNetworkList()) {
            networkJComboBox.addItem(network);
        }
    }

    private void populateEnterpriseComboBox(Network network) {
        enterpriseJComboBox.removeAllItems();

        for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
            enterpriseJComboBox.addItem(enterprise);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        shapePainter1 = new org.jdesktop.swingx.painter.ShapePainter();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        networkJComboBox = new javax.swing.JComboBox();
        enterpriseJComboBox = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        usernameJTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        nameJTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        passwordJPasswordField = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        mobileJTextfield = new javax.swing.JFormattedTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        enterpriseJTable = new javax.swing.JTable();
        headingLabel = new javax.swing.JLabel();
        submitJButton1 = new javax.swing.JButton();

        shapePainter1.setShape(null);

        setPreferredSize(new java.awt.Dimension(629, 430));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder1 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder1.setShowLeftShadow(true);
        dropShadowBorder1.setShowTopShadow(true);
        jPanel1.setBorder(dropShadowBorder1);
        jPanel1.setMinimumSize(new java.awt.Dimension(418, 110));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 220));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Network");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        networkJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        networkJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                networkJComboBoxActionPerformed(evt);
            }
        });
        jPanel1.add(networkJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 230, -1));

        enterpriseJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(enterpriseJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 230, -1));

        jLabel3.setText("Enterprise");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 410, 70));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder2 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder2.setShowLeftShadow(true);
        dropShadowBorder2.setShowTopShadow(true);
        jPanel2.setBorder(dropShadowBorder2);
        jPanel2.setPreferredSize(new java.awt.Dimension(400, 220));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Username");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        usernameJTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                usernameJTextFieldFocusLost(evt);
            }
        });
        jPanel2.add(usernameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 136, -1));

        jLabel4.setText("Password");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        nameJTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                nameJTextFieldFocusLost(evt);
            }
        });
        jPanel2.add(nameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 134, -1));

        jLabel5.setText("Name");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        passwordJPasswordField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordJPasswordFieldFocusLost(evt);
            }
        });
        jPanel2.add(passwordJPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 134, -1));

        jLabel6.setText("Emergency number");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        try {
            mobileJTextfield.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        mobileJTextfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                mobileJTextfieldFocusLost(evt);
            }
        });
        jPanel2.add(mobileJTextfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 130, -1));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 410, 150));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder3 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder3.setShadowColor(new java.awt.Color(204, 204, 204));
        dropShadowBorder3.setShowLeftShadow(true);
        dropShadowBorder3.setShowTopShadow(true);
        jPanel3.setBorder(dropShadowBorder3);
        jPanel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel3.setPreferredSize(new java.awt.Dimension(400, 220));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        enterpriseJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Enterprise Name", "Network", "Username", "Em Number"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        enterpriseJTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                enterpriseJTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(enterpriseJTable);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 370, 90));

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 410, 160));

        headingLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        headingLabel.setText("Add / Update Admins");
        add(headingLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        submitJButton1.setBackground(new java.awt.Color(255, 255, 255));
        submitJButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        submitJButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imgs/math-add-icon.png"))); // NOI18N
        submitJButton1.setText("Add");
        submitJButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        submitJButton1.setPreferredSize(new java.awt.Dimension(75, 31));
        submitJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJButton1ActionPerformed(evt);
            }
        });
        add(submitJButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 260, 35));
    }// </editor-fold>//GEN-END:initComponents

    private void networkJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_networkJComboBoxActionPerformed

        Network network = (Network) networkJComboBox.getSelectedItem();
        if (network != null) {
            populateEnterpriseComboBox(network);
        }


    }//GEN-LAST:event_networkJComboBoxActionPerformed

    private void submitJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJButton1ActionPerformed

        Enterprise enterprise = (Enterprise) enterpriseJComboBox.getSelectedItem();

        String username = usernameJTextField.getText();
        String password = String.valueOf(passwordJPasswordField.getPassword());
        String name = nameJTextField.getText();

        if(UIUtilities.isEmpty(usernameJTextField) || UIUtilities.isEmpty(passwordJPasswordField) ||
                UIUtilities.isEmpty(nameJTextField) || UIUtilities.isEmpty(mobileJTextfield)){
            JOptionPane.showMessageDialog(null, "Some fields are Empty!!!");
            return;
        }
        if (enterprise.getUserAccountDirectory().checkIfUsernameIsUnique(username)) {
            Employee employee = enterprise.getEmployeeDirectory().createEmployee(name);
            employee.setMobileNum(mobileJTextfield.getText());
            UserAccount account = enterprise.getUserAccountDirectory().createUserAccount(username, password, employee, new AdminRole());
                JOptionPane.showMessageDialog(null, "Admin User Successfully created!!");
            } else {
               JOptionPane.showMessageDialog(null, "Admin name is already present!!");
                return;
            }
        
        

        populateTable();
    }//GEN-LAST:event_submitJButton1ActionPerformed

    private void passwordJPasswordFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordJPasswordFieldFocusLost
        // TODO add your handling code here:
        if (UIUtilities.isEmpty(passwordJPasswordField)) {
            passwordJPasswordField.setText("");
            passwordJPasswordField.setBackground(Color.yellow);
            //evt.consume();
            JOptionPane.showMessageDialog(null, "Password is Empty");
        } else {
            passwordJPasswordField.setBackground(Color.white);

        }
    }//GEN-LAST:event_passwordJPasswordFieldFocusLost

    private void nameJTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameJTextFieldFocusLost
        // TODO add your handling code here:
        if (UIUtilities.isEmpty(nameJTextField)) {
            nameJTextField.setText("");
            nameJTextField.setBackground(Color.yellow);
            //evt.consume();
            JOptionPane.showMessageDialog(null, "Name field is Empty");
        } else {
            nameJTextField.setBackground(Color.white);

        }
    }//GEN-LAST:event_nameJTextFieldFocusLost

    private void usernameJTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameJTextFieldFocusLost
        // TODO add your handling code here:
        if (UIUtilities.isEmpty(usernameJTextField)) {
            usernameJTextField.setText("");
            usernameJTextField.setBackground(Color.yellow);
            //evt.consume();
            JOptionPane.showMessageDialog(null, "Username field is Empty");
        } else {
            usernameJTextField.setBackground(Color.white);

        }
    }//GEN-LAST:event_usernameJTextFieldFocusLost

    private void mobileJTextfieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mobileJTextfieldFocusLost
        // TODO add your handling code here:
        if (UIUtilities.isEmpty(mobileJTextfield)) {
            mobileJTextfield.setText("");
            mobileJTextfield.setBackground(Color.yellow);
            //evt.consume();
            JOptionPane.showMessageDialog(null, "Mobile Number is Empty is Empty");
        } else {
            mobileJTextfield.setBackground(Color.white);
            //msgLabel.setVisible(false);

        }
    }//GEN-LAST:event_mobileJTextfieldFocusLost

    private void enterpriseJTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enterpriseJTableMouseClicked
        // TODO add your handling code here:
 
    }//GEN-LAST:event_enterpriseJTableMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox enterpriseJComboBox;
    private javax.swing.JTable enterpriseJTable;
    private javax.swing.JLabel headingLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JFormattedTextField mobileJTextfield;
    private javax.swing.JTextField nameJTextField;
    private javax.swing.JComboBox networkJComboBox;
    private javax.swing.JPasswordField passwordJPasswordField;
    private org.jdesktop.swingx.painter.ShapePainter shapePainter1;
    private javax.swing.JButton submitJButton1;
    private javax.swing.JTextField usernameJTextField;
    // End of variables declaration//GEN-END:variables
}
